import { StarterPack } from './types';

export const STARTER_PACKS: StarterPack[] = [
  {
    id: 'more_enquiries',
    name: 'More enquiries',
    description: 'New job enquiries hit your phone in 60 seconds. Lead gen, outreach, scraping, Google Maps, LinkedIn — all automated.',
    templates: ['lead_gen', 'marketing'],
    default_packs: ['email_pack', 'crm_pack', 'calendar_pack'],
    default_channels: ['email', 'linkedin', 'sms'],
    price_cents: 19700,
  },
  {
    id: 'more_closes',
    name: 'More closes',
    description: 'Quote follow-ups at 24h, 48h, 72h. Booking reminders. Meeting no-shows eliminated. AI qualifies and closes while you sleep.',
    templates: ['sales'],
    default_packs: ['crm_pack', 'calendar_pack', 'pricing_pack'],
    default_channels: ['email', 'sms', 'whatsapp'],
    price_cents: 19700,
  },
  {
    id: 'more_attention',
    name: 'More attention',
    description: 'Posts on Facebook, Instagram, LinkedIn — done. Videos, carousels, copy. You don't write a word.',
    templates: ['content', 'marketing'],
    default_packs: ['email_pack', 'calendar_pack'],
    default_channels: ['linkedin', 'instagram', 'youtube'],
    price_cents: 19700,
  },
  {
    id: 'less_admin',
    name: 'Less admin',
    description: 'Invoices sent automatically after every job. Hiring, onboarding, complaints, errors — all handled without you.',
    templates: ['operations', 'finance'],
    default_packs: ['email_pack', 'escalation_pack'],
    default_channels: ['email', 'internal'],
    price_cents: 19700,
  },
  {
    id: 'smarter_moves',
    name: 'Smarter moves',
    description: 'What are your competitors doing? What's trending? Real-time insights so you're always a step ahead.',
    templates: ['intelligence'],
    default_packs: ['email_pack', 'escalation_pack'],
    default_channels: ['email', 'internal'],
    price_cents: 19700,
  },
  {
    id: 'happier_clients',
    name: 'Happier clients',
    description: 'AI answers the phone while you're on the tools. WhatsApp replies at 9pm. Support tickets resolved. Clients feel looked after.',
    templates: ['customer_service'],
    default_packs: ['email_pack', 'faq_pack', 'escalation_pack'],
    default_channels: ['email', 'webchat', 'whatsapp'],
    price_cents: 19700,
  },
];

export const TEMPLATES = [
  { id: 'lead_gen',          name: 'More enquiries',   category: 'Revenue',  description: 'Leads hit your phone in 60 seconds', icon: '📲' },
  { id: 'sales',             name: 'More closes',       category: 'Revenue',  description: 'Quote follow-ups and deal closing automated', icon: '🤝' },
  { id: 'content',           name: 'More attention',    category: 'Growth',   description: 'Social posts, videos, copy — done for you', icon: '📣' },
  { id: 'marketing',         name: 'More reach',        category: 'Growth',   description: 'Ads, outreach, campaigns on autopilot', icon: '🚀' },
  { id: 'customer_service',  name: 'Happier clients',   category: 'Support',  description: 'Calls, chats, tickets — handled without you', icon: '🎧' },
  { id: 'operations',        name: 'Less admin',        category: 'Ops',      description: 'Invoices, hiring, onboarding — automated', icon: '⚙️' },
  { id: 'finance',           name: 'No chasing invoices', category: 'Finance', description: 'Invoice sent, payment chased, done', icon: '💰' },
  { id: 'intelligence',      name: 'Smarter moves',     category: 'Intel',    description: 'Competitor intel and market insights in real time', icon: '🔍' },
  { id: 'hr',                name: 'Better hires',      category: 'People',   description: 'Post jobs, screen applicants, onboard fast', icon: '👥' },
  { id: 'platform',          name: 'Everything connected', category: 'Platform', description: 'MCP integrations — wire any tool to any agent', icon: '🔧' },
  { id: 'grants',            name: 'Grants found',      category: 'Finance',  description: 'Grant intelligence and application assistance', icon: '🏛️' },
];
